header: 
  seq: 0
  stamp: 
    secs: 1385661874
    nsecs: 56044628
  frame_id: world_link
id: table_plate_link
type: 
  key: ''
  db: ''
primitives: []
primitive_poses: []
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 1
---
header: 
  seq: 1
  stamp: 
    secs: 1385661874
    nsecs: 56044628
  frame_id: world_link
id: table_plate_link
type: 
  key: ''
  db: ''
primitives: []
primitive_poses: []
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 1
---
header: 
  seq: 2
  stamp: 
    secs: 1385661874
    nsecs: 256309065
  frame_id: world_link
id: cylinder1
type: 
  key: ''
  db: ''
primitives: []
primitive_poses: []
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 1
---
header: 
  seq: 3
  stamp: 
    secs: 1385661874
    nsecs: 256309065
  frame_id: world_link
id: cylinder1
type: 
  key: ''
  db: ''
primitives: []
primitive_poses: []
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 1
---
header: 
  seq: 4
  stamp: 
    secs: 1385661874
    nsecs: 456531615
  frame_id: world_link
id: table_plate_link
type: 
  key: ''
  db: ''
primitives: 
  - 
    type: 1
    dimensions: [0.9, 2.3, 0.1]
primitive_poses: 
  - 
    position: 
      x: 0.371
      y: 0.81
      z: 0.05
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 0
---
header: 
  seq: 5
  stamp: 
    secs: 1385661874
    nsecs: 456620043
  frame_id: world_link
id: obstacle
type: 
  key: ''
  db: ''
primitives: 
  - 
    type: 1
    dimensions: [0.5, 0.1, 0.3]
primitive_poses: 
  - 
    position: 
      x: 0.25
      y: 0.25
      z: 0.25
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 0
---
header: 
  seq: 6
  stamp: 
    secs: 1385661874
    nsecs: 456708167
  frame_id: world_link
id: cylinder1
type: 
  key: ''
  db: ''
primitives: 
  - 
    type: 3
    dimensions: [0.3, 0.04]
primitive_poses: 
  - 
    position: 
      x: 0.2
      y: 0.0
      z: 0.25
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
meshes: []
mesh_poses: []
planes: []
plane_poses: []
operation: 0
---
